services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    network_mode: host
    volumes:
      - ./mounts/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "${DB_HOST:-localhost}:${DB_PORT:-5433}/${DB_NAME:-postgres}?sslmode=disable"
      DATA_SOURCE_USER: ${DB_USER:-waymark}
      DATA_SOURCE_PASS: ${DB_PASS:-waymark}
    network_mode: host
    restart: unless-stopped

  pg-exporter:
    image: pgsty/pg_exporter
    environment:
      PG_EXPORTER_URL: "postgres://${DB_USER:-waymark}:${DB_PASS:-waymark}@${DB_HOST:-localhost}:${DB_PORT:-5433}/${DB_NAME:-postgres}"
    network_mode: host
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
    network_mode: host
    volumes:
      - ./mounts/grafana-provisioning/:/etc/grafana/provisioning:ro
      - ./mounts/grafana-dashboards/:/dashboards:ro
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
