{
 "title": "PGRDS Instance",
 "description": "PostgreSQL Monitoring for Remote RDS instances (with limited metrics)",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance",
  "PGRDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\", datname!~\"template0|template1|postgres|rdsadmin|polardb_admin\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Cluster" }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (pg_up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:active_time_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg_uptime{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (address) (label_join(pg_meta_info{ins=\"$ins\"}, \"address\", \":\", \"ip\", \"listen_port\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_in_recovery{ins=\"$ins\"}",
     "legendFormat": "recovery"
    },
    {
     "expr": "(pg_recv_init_lsn{ins=\"$ins\"} > bool 0) or on() vector(0)",
     "legendFormat": "{{ sender_host }} "
    },
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Downstream"
    },
    {
     "expr": "pg_sync_standby_enabled{ins=\"$ins\"}",
     "legendFormat": "Sync Commit"
    },
    {
     "expr": "count by (ins)(pg_pubrel_count{ins=\"$ins\"}) > bool 0 or on() vector(0)",
     "legendFormat": "Publication"
    },
    {
     "expr": "count by (ins)(pg_sub_id{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Subscription"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_uptime{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_version{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_conf_reload_time{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg:ins:timeline{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_is_wal_replay_paused{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:active_time_rate1m{ins=\"$ins\"} / pg:ins:xact_total_rate1m{ins=\"$ins\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "Conn%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:active_backends{ins=\"$ins\"}",
     "legendFormat": "Active Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:ixact_backends{ins=\"$ins\"})",
     "legendFormat": "iXact Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:tup_fetched_rate1m{ins=\"$ins\"}",
     "legendFormat": "Row Fetch"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:tup_modified_rate1m{ins=\"$ins\"}",
     "legendFormat": "Row Change"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:blks_read_1m{ins=\"$ins\"}) * 4096",
     "legendFormat": "Blks Read"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:age{ins=\"$ins\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{ins=\"$ins\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Load, 1 = 100% one cpu core usage.\nCalculated by session active time  (PG14+)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Load for Instances / Databases in last 5 minutes\nload 1 = 100% usage of 1 core cpu time",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:active_time_rate1m{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{ins=\"$ins\", alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Transaction Commits / Rollbacks (rate5m)",
   "type": "timeseries",
   "description": "Rate in last 5min of:\n\n\npg_stat_database. xact_commit: Number of transactions in this database that have been committed\n\npg_stat_database. xact_rollback: Number of transactions in this database that have been rolled back\n\non this postgres instance.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate5m{ins=\"$ins\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_rollback_rate5m{ins=\"$ins\"})",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Transaction RT (1m)",
   "type": "timeseries",
   "description": "pg_stat_database: active_time / (xact_commit + xact_rollback)\n\n\nTime spent executing SQL statements in this instance / Number of transactions in this instance in last 1 minute\n\n\nOnly available on PG14+\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:ins:active_time_rate1m{ins=\"$ins\"} / pg:ins:xact_total_rate1m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pg:db:active_time_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'} / pg:db:xact_total_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS by Database (rate1m)",
   "type": "timeseries",
   "description": "Transaction Committed rate in last 1 minute, group on database level",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Load (rate1m)",
   "type": "timeseries",
   "description": "Postgres Load Index in last 1 minutes\n\n\nrate(pg_stat_database.active_time[5m])\n\n\nload 1 = 100% usage of one cpu core.\n\n\nCalculated by session active time  (PG14+) @ database level.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:active_time_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Fetched (rate1m)",
   "type": "timeseries",
   "description": "Tuples fetched from databases r/s in last minute, group by database on this instance. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_tup_fetched{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Modified (rate1m)",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete r/s in last minute, on this instance",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "timeseries",
   "description": "Table lock categorized in to 3 major categories:\nRead locks, Write Locks, and Exclusive locks.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xlock_count{ins=\"$ins\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "pg:ins:wlock_count{ins=\"$ins\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "pg:ins:rlock_count{ins=\"$ins\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "description": "Table Locks in 8 different mode, on this instance",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{ins=\"$ins\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "SAGE",
   "type": "timeseries",
   "description": "Very long transactions, max elapse time (y) group by session state. On this postgres instance",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{ins=\"$ins\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "description": "Ratio of database session / max allowed sesion per database. the limit is min of max_connections and database's connection limit.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Transaction Backends",
   "type": "timeseries",
   "description": "Idle in Transaction backend number of all databases in this instance.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "timeseries",
   "description": "Number of database backend process / session by database.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "New Sessions (increase1m)",
   "type": "timeseries",
   "description": "Newly established session on each database.\nIncrease number of last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_db_sessions{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Backends by State",
   "type": "timeseries",
   "description": "Backend number group by state in this instance.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Type",
   "type": "timeseries",
   "description": "Backend number group by backend type in this instance.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by (type) (pg_backend_count{ins=\"$ins\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Max Conn Lifespan",
   "type": "timeseries",
   "description": "Max connection duration group by session time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_conn_duration{ins=\"$ins\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Wait Event",
   "type": "timeseries",
   "description": "Backend number group by wait event type in this instance.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by (event) (pg_wait_count{ins=\"$ins\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Active% (of Session Time)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_active_time{ins=\"$ins\"}[1m]))\n/ sum by (datname) (rate(pg_db_session_time{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Sessions Failure in 1m",
   "type": "timeseries",
   "description": "Abandon: Number of database sessions to this database that were terminated because connection to the client was lost\n\n\nFatal: Number of database sessions to this database that were terminated by fatal errors\n\n\nKilled: Number of database sessions to this database that were terminated by operator intervention\n\n\navailable on PG 14+",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_db_sessions_abandoned{ins=\"$ins\"}[1m]))",
     "legendFormat": "[Abandoned] : {{ datname }}"
    },
    {
     "expr": "sum by (datname) (increase(pg_db_sessions_fatal{ins=\"$ins\"}[1m]))",
     "legendFormat": "[Fatal] : {{ datname }}"
    },
    {
     "expr": "sum by (datname) (increase(pg_db_sessions_killed{ins=\"$ins\"}[1m]))",
     "legendFormat": "[Killed] : {{ datname }}"
    }
   ]
  },
  { "title": "Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "LSN Progress (rate1m)",
   "type": "timeseries",
   "description": "Rate of lsn in last minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Age Usage",
   "type": "timeseries",
   "description": "XID Usage of each databases in this instance.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Cluster Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database WAL/Log Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\", datname=~\"(log|wal)\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Checkpoint Scheduled / Requested",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "pg_bgwriter_checkpoints_timed{ins=\"$ins\"}",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "pg_bgwriter_checkpoints_req{ins=\"$ins\"} ",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Checkpoint Time : Sync/Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_checkpoint_sync_time{ins=\"$ins\"}[1m])",
     "legendFormat": "Sync"
    },
    {
     "expr": "- rate(pg_bgwriter_checkpoint_write_time{ins=\"$ins\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "BGWriter Buffer Flush",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_clean{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Clean"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_checkpoint{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_backend{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "BGWriter Buffer Alloc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_alloc{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Alloc"
    }
   ]
  },
  {
   "title": "Blocks Access 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:blks_access_1m{ins=\"$ins\"}) * 4096",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Read (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:blks_read_1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'}) * 4096",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Blocks Read/Write Time Spent Rate1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:blk_read_time_seconds_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'})",
     "legendFormat": "▲ {{ datname }}"
    },
    {
     "expr": "- sum by (datname) (pg:db:blk_write_time_seconds_rate1m{ins=\"$ins\", datname!~'rdsadmin|polardb_admin|template\\\\d'})",
     "legendFormat": "▼ {{ datname }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Database Size",
   "type": "timeseries",
   "description": "Database size on cluster primary",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_size_bytes{ins=\"$ins\", datname!~'wal|log|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Size Delta 10m",
   "type": "timeseries",
   "description": "Database Size Change on Cluster Primary in Last 10 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(pg_size_bytes{ins=\"$ins\", datname!~'wal|log|template\\\\d'}[10m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS by Database (rate1m)",
   "type": "timeseries",
   "description": "Database Transaction Commit Rate in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$ins\", datname!~'template\\\\d'})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session by Database",
   "type": "timeseries",
   "description": "Active processs for each database in this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Transaction Backends",
   "type": "timeseries",
   "description": "number of dangerous idle in transaction backend in different database amoung this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 133 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "description": "Connection used ratio of min(\n  max_connections @ instance level,\n  connlimit @ database level\n)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "New Sessions (incr1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "increase(pg_db_sessions{ins=\"$ins\", datname!~'template\\\\d'}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Fetched",
   "type": "timeseries",
   "description": "Tuples fetched from databases among this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_tup_fetched{ins=\"$ins\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Modified",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster group by database",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$ins\", datname!~'template\\\\d'}[1m])) by (datname)",
     "legendFormat": "INSERT.{{ datname }}"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$ins\", datname!~'template\\\\d'}[1m])) by (datname)",
     "legendFormat": "UPDATE.{{ datname }}"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$ins\", datname!~'template\\\\d'}[1m])) by (datname)",
     "legendFormat": "DELETE.{{ datname }}"
    }
   ]
  },
  { "title": "Table & Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Table Scan (scan/s)",
   "type": "timeseries",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname,relname) (\n    pg:table:scan_rate1m{ins=\"$ins\", datname!~'template\\\\d'}\n)",
     "legendFormat": "{{ datname }}.{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname,relname)  (\n    rate(pg_table_tup_read{ins=\"$ins\", datname!~'template\\\\d'}[1m])\n)",
     "legendFormat": "{{ datname }}.{{ relname }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "{{ datname }}.{{ query }}"
    }
   ]
  },
  {
   "title": "Query Time ",
   "type": "timeseries",
   "description": "Top Query Time Spent among this cluster",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname!~'template\\\\d'}[1m])",
     "legendFormat": "{{ datname }}.{{ query }}"
    }
   ]
  }
 ]
}