{
 "title": "PGSQL Exporter",
 "description": "PostgreSQL Instance Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\",datname!~'postgres|template0|template1'}, datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Cluster" },
    { "expr": "1", "legendFormat": "IP" },
    { "expr": "1", "legendFormat": "Name" }
   ]
  },
  {
   "title": "Export Status",
   "type": "table",
   "description": "Exporter Aliveness Status in ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max by (ins) (pg_exporter_agent_up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer_exporter_agent_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pgbackrest_exporter_agent_up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg_exporter_uptime{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer_exporter_uptime{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgbouncer_exporter"
    },
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "patroni_up{ins=\"$ins\"}",
     "legendFormat": "patroni"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgbackrest_exporter"
    }
   ]
  },
  { "title": "Global Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg_exporter_agent_up{}", "legendFormat": "{{ instance }}" },
    { "expr": "pgbouncer_exporter_agent_up{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (ins) (pg_exporter_agent_up{})"
    },
    {
     "expr": "max by (ins) (pgbouncer_exporter_agent_up{})"
    },
    {
     "expr": "max by (ins) (pg_exporter_uptime{})"
    },
    {
     "expr": "max by (ins) (pgbouncer_exporter_uptime{})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_exporter_scrape_duration{}", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "Global Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_exporter_uptime{}", "legendFormat": "{{ ins }}" },
    { "expr": "pgbouncer_exporter_uptime{}", "legendFormat": "{{ ins }}" }
   ]
  },
  {
   "title": "Global Error Rate",
   "type": "timeseries",
   "description": "Error Increase in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_scrape_error_count{}[1m])",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_scrape_error_count{}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_uptime{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_uptime{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Exporter Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_scrape_duration{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_scrape_duration{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Errors Count Per Minute",
   "type": "timeseries",
   "description": "Error Increase in last 1 minute",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_scrape_error_count{ins=\"$ins\"}[1m])",
     "legendFormat": "postgres"
    },
    {
     "expr": "increase(pgbouncer_exporter_scrape_error_count{ins=\"$ins\"}[1m])",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Scrape Duration (per Server)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_server_scrape_duration{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    },
    {
     "expr": "pgbouncer_exporter_server_scrape_duration{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Scrape Count Per Minute",
   "type": "timeseries",
   "description": "Scrape Count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_server_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ datname }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  { "title": "Collectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query) (increase(pg_exporter_query_scrape_error_count{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query) (pg_exporter_query_scrape_metric_count{ins=\"$ins\"})",
     "legendFormat": "{{query}}"
    },
    {
     "expr": "sum by (query) (pgbouncer_exporter_query_scrape_metric_count{ins=\"$ins\"})",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_duration{ins=\"$ins\"}[1m]) / \nincrease(pg_exporter_query_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ datname }}.{{ query }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_duration{ins=\"$ins\"}[1m]) / \nincrease(pgbouncer_exporter_query_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "pgbouncer.{{ query }}"
    }
   ]
  },
  {
   "title": "Query Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_hit_count{ins=\"$ins\"}[5m]) / \nincrease(pg_exporter_query_scrape_total_count{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ datname }}.{{query}}"
    },
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_hit_count{ins=\"$ins\"}[5m]) / \nincrease(pgbouncer_exporter_query_scrape_total_count{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ datname }}.{{query}}"
    }
   ]
  },
  {
   "title": "Cache TTL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_query_cache_ttl{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}.{{ query }}"
    },
    {
     "expr": "pgbouncer_exporter_query_cache_ttl{ins=\"$ins\"}",
     "legendFormat": "pgbouncer. {{ query }}"
    }
   ]
  },
  { "title": "PG Exporter Logs: ${ins}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "description": "pg_exporter logs count",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(({ip=\"$ip\", src=\"syslog\"} |~ \"pg_exporter\")[$__interval])"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "description": "Recent logs for pgbouncer & patroni & postgres",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{ip=\"$ip\"} |~ \"pg_exporter\""
    }
   ]
  }
 ]
}